/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://6zyzbuahtrarvdje4cq6z4vxcy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4qnusimqezf53o7y525xzna3ua",
    "aws_cognito_identity_pool_id": "us-east-1:2fc15ac7-cb7e-4951-b560-b6155de38dd3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7VryRwguo",
    "aws_user_pools_web_client_id": "3mglrtrumpnbmsttik3hrkhud9",
    "oauth": {}
};


export default awsmobile;
